*  XPiratez Research Tree Explorer (aka xresearch)
`xresearch` is a web-based application meant to allow exploration of the XPiratez research tree data.

This web application is released into the public domain with no license, copyright or warranty claims made. Dependent libraries carry their own licenses as part of their source (or implied by the license available at their repository/website-of-record).

For better or worse, this app was developed and tested in Chrome, so use that if you want it to run w/ relatively little hassle.

This application was conceived-of and developed-by Jeffery Olson for the sake of exploring the data and as an opportunity to develop with tools like React, cytoscape.js, etc. Also, `xresearch` has a somewhat unorthodox application structure, owing to my still-evolving grasp of assorted haute webdev tools/pipelines (and trying to manage the cognitive load thereof). So it's not structured according to what's observed as best practice. Please do forgive me.

** Dependencies
- XPiratez, of course, without whom we wouldn't have the glorious data to explore
  - `xresearch` relies upon a copy of the `Piratez.rul` and `Piratez_lang.rul` files, provided as a part of the XPiratez mod distro. They may have been modified to address YAML parsing issues, only.
- node.js for the ruleset parser and dev server
- `js-yaml` for YAML parsing (the format for the `.rul` file representation)
- `simple-grid.css` for a barebones CSS grid
- `lodash` is great; everyone should use it
- `cytoscape.js` a wonderful and *performant* graph viz library (funded with public money, no less!)
- `redux` for view state management
- `react` as a view engine and structural pattern
- `font-awesome` for icons

** Run development server locally
- have recent node.js + npm installed
- clone this repository to your local machine
- entire repo and run `npm install` command
- `node app.js` to bring up the development server
- Once you see "data is parsed" displayed, you can navigate to `http://localhost:3000` in Chrome to see the app

** Update the Piratez.rul/Piratez_lang.rul files & regenerate static HTML
TODO

** Pending work items
- [X] write Piratez/Piratez_lang.rul files parse
- [X] import parsed JSON into a static html display
- [X] Basic, whole-tree display/visualization
- [X] integrate react and refactor to component
- [X] Integrate redux for basic view-state management
- [X] node search + sidebar view
  - [X] utilizing the input on the top-right of the page, search the tree topic names for matches
  - [X] display them in a <ul> list on the sidebar
- [-] add node details sidebar view (include <ul>'s with dependencies, unlocks, getOneFree, requires (non-interactive))
  - [X] display dependencies
  - [ ] display unlocks
  - [ ] display getOneFree
- [ ] integrate webpack bundling
- [ ] fix dark text coloring in page style
- [ ] when "searchText" is empty, return nothing; when > 20 results, return nothing
- [ ] CYTOSCAPE: Clicking on a graph node dispatches NODE_SELECTION action
- [ ] PARSER: move keysIndexMap into parser from sidebar or whatever
- [ ] PARSER: map inverses of data in .rul entries (get terminology from tech viewer in client) (should be O(2) ):
  - [ ] depended-upon-by
  - [ ] unlocked-by
  - [ ] get-for-free-from
  - [ ] add all of the above to NodeDetails
- [ ] CYTOSCAPE: show sub-graph when NodeDetail is displayed for a given node
  - [ ] trim the cytoscape graph display to contain the selected node (bolded/enlarged or whatever), along with its immediate neighbors and the edges that connect them
  - [ ] try to use the "cose" layout
- [ ] add "Show Entire Research Tree" button/link to top of page to reset the display
- [ ] static HTML generation for running as a github site
- [ ] router support in URL (probably implies a more advanced view manager?)
- [ ] show ruleset version in page display
- [ ] extra double-plus gold plating: Create a webfont based upon the XCOM bitmap fontset and use that in xresearch; enforce overall mid-90s DOS euro-game aesthetic
- [ ] PARSER: Integrate "vanilla language files" in common/en-US.yml , standard/xcom1/Language , etc for more str keys
