// sidebar modes
const constants ={
    DEFAULT_SEARCHTEXT: 'Search by topic...',
    SIDEBAR_MODE_SPLASH: 'SIDEBAR_MODE_SPLASH',
    SIDEBAR_MODE_SEARCH_RESULTS: 'SIDEBAR_MODE_SEARCH_RESULTS',
    SIDEBAR_MODE_NODE_DETAILS: 'SIDEBAR_MODE_NODE_DETAILS',

    SEARCH_TEXT_CHANGE: 'SEARCH_TEXT_CHANGE',
    NODE_SELECTION: 'NODE_SELECTION',
    GRAPH_UPDATING_CHANGE: 'GRAPH_UPDATING_CHANGE',
    GRAPH_FILTERING_CATEGORY_CHANGE: 'GRAPH_FILTERING_CATEGORY_CHANGE',

    COLOR_RED: '#ee5f5b',
    COLOR_GREEN: '#62c462',
    COLOR_BLUE:'#5bc0de',
    COLOR_ORANGE: '#f89406',
    COLOR_GRAY_LIGHT: '#e9ecef'
};

export default constants;
