// sidebar modes
const constants ={
    DEFAULT_SEARCHTEXT: 'Search by topic...',
    SIDEBAR_MODE_SPLASH: 'SIDEBAR_MODE_SPLASH',
    SIDEBAR_MODE_SEARCH_RESULTS: 'SIDEBAR_MODE_SEARCH_RESULTS',
    SIDEBAR_MODE_NODE_DETAILS: 'SIDEBAR_MODE_NODE_DETAILS',

    SEARCH_TEXT_CHANGE: 'SEARCH_TEXT_CHANGE',
    NODE_SELECTION: 'NODE_SELECTION',
    GRAPH_UPDATING_CHANGE: 'GRAPH_UPDATING_CHANGE',
    GRAPH_FILTERING_CATEGORY_CHANGE: 'GRAPH_FILTERING_CATEGORY_CHANGE',
    VIEWPORT_CHANGE: 'VIEWPORT_CHANGE',

    COLOR_RED: '#ee5f5b',
    COLOR_GREEN: '#62c462',
    COLOR_BLUE:'#5bc0de',
    COLOR_ORANGE: '#f89406',
    COLOR_GRAY_LIGHT: '#e9ecef',
    COLOR_GRAY_DARK: '#141618',

    VIEWPORT_OFFSET: 140,

    CY_CONTAINER_ID: 'cy-container',

    HREF_XPIRATEZ: 'https://openxcom.org/forum/index.php?topic=3626.0',
    HREF_XRESEARCH: 'https://github.com/olsonjeffery/xresearch'
};

export const Constants = constants;
