// sidebar modes
const constants ={
    DEFAULT_SEARCHTEXT: 'Enter topic to search',
    SIDEBAR_MODE_SPLASH: 'SIDEBAR_MODE_SPLASH',
    SIDEBAR_MODE_SEARCH_RESULTS: 'SIDEBAR_MODE_SEARCH_RESULTS',
    SIDEBAR_MODE_NODE_DETAILS: 'SIDEBAR_MODE_NODE_DETAILS',

    SEARCH_TEXT_CHANGE: 'SEARCH_TEXT_CHANGE',
    NODE_SELECTION: 'NODE_SELECTION',
    GRAPH_UPDATING_CHANGE: 'GRAPH_UPDATING_CHANGE',
    GRAPH_FILTERING_CATEGORY_CHANGE: 'GRAPH_FILTERING_CATEGORY_CHANGE'
};

export default constants;
